#!/usr/bin/env python

import json
import sys
import argparse
import pymongo

parser = argparse.ArgumentParser(description='Reimzul CentOS distributed build query tool')

parser.add_argument('-s', '--status', action="store", dest="status", required=True, help='The status to query for [Building,Done,Success,Failed]')
parser.add_argument('-t', '--target', action="store", dest="target", help='The target repo to query for, with the arch specified [example: c7.1810.00.armhfp]')

results = parser.parse_args()
client = pymongo.MongoClient()
db = client.reimzul  
builds = db.notify_history

query = {}
query['latest_build'] = True
query['status'] = results.status
if results.target is not None:
  query['target'] = results.target

for job in builds.find( query ):
  print '%s (arch: %s, status: %s, builder: %s)' % (job['srpm'],job['arch'],job['status'],job['builder_fqdn'])

